name: scan-simples
on: workflow_dispatch

jobs:
  scan:
    name: scan-simples
    runs-on: ubuntu-20.04
    env:
      TF_VERSION: "1.0.11"
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Terraform 
      run: |
        cd terraform
        terraform init
    
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
